language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Willanzhang"
  - git config user.email "631871612@qq.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/Willanzhang/Willanzhang.github.io
